#ifndef GC__DSP_EXTENDED_INSTRUCTIONS_H
#define GC__DSP_EXTENDED_INSTRUCTIONS_H

#include "DSP.h"

DSP_EXT_INSTR(DSP_EXT_DR);
DSP_EXT_INSTR(DSP_EXT_IR);
DSP_EXT_INSTR(DSP_EXT_NR);

DSP_EXT_INSTR(DSP_EXT_MV);

DSP_EXT_INSTR(DSP_EXT_S);
DSP_EXT_INSTR(DSP_EXT_SN);

DSP_EXT_INSTR(DSP_EXT_L);
DSP_EXT_INSTR(DSP_EXT_LN);

DSP_EXT_INSTR(DSP_EXT_LS);
DSP_EXT_INSTR(DSP_EXT_LSN);
DSP_EXT_INSTR(DSP_EXT_LSM);
DSP_EXT_INSTR(DSP_EXT_LSNM);

DSP_EXT_INSTR(DSP_EXT_SL);
DSP_EXT_INSTR(DSP_EXT_SLN);
DSP_EXT_INSTR(DSP_EXT_SLM);
DSP_EXT_INSTR(DSP_EXT_SLNM);

DSP_EXT_INSTR(DSP_EXT_LD);
DSP_EXT_INSTR(DSP_EXT_LDN);
DSP_EXT_INSTR(DSP_EXT_LDM);
DSP_EXT_INSTR(DSP_EXT_LDNM);

DSP_EXT_INSTR(DSP_EXT_LDAX);
DSP_EXT_INSTR(DSP_EXT_LDAXN);
DSP_EXT_INSTR(DSP_EXT_LDAXM);
DSP_EXT_INSTR(DSP_EXT_LDAXNM);

DSP_EXT_INSTR(DSP_EXT_NOP);
DSP_EXT_INSTR(DSP_EXT_INVALID);

#endif //GC__DSP_EXTENDED_INSTRUCTIONS_H
