#ifndef GC__DSP_INSTRUCTIONS_H
#define GC__DSP_INSTRUCTIONS_H

#include "DSP.h"

DSP_INSTR(DSP_unimplemented);

DSP_INSTR(DSP_0000_0000);
DSP_INSTR(DSP_SBSET);
DSP_INSTR(DSP_SET16);
DSP_INSTR(DSP_SET40);
DSP_INSTR(DSP_SET15);
DSP_INSTR(DSP_CLR15);
DSP_INSTR(DSP_M0);
DSP_INSTR(DSP_M2);


#endif //GC__DSP_INSTRUCTIONS_H
