#ifndef GC__FLAGS_H
#define GC__FLAGS_H

#define VERBOSITY_ALL 0
#define VERBOSITY_DEBUG 1
#define VERBOSITY_INFO 2
#define VERBOSITY_WARN 3
#define VERBOSITY_ERROR 4
#define VERBOSITY_MAX VERBOSITY_ERROR

#define COMPONENT_CPU 0x01
#define COMPONENT_MMU 0x02
#define COMPONENT_HW_REG 0x04
#define COMPONENT_CP 0x08
#define COMPONENT_FLIPPER 0x10
#define COMPONENT_SCHEDULER 0x20

#ifndef NDEBUG
// change to change verbosity / component logging:
#define VERBOSITY VERBOSITY_WARN
#define COMPONENT_FLAGS (COMPONENT_CP | COMPONENT_FLIPPER | COMPONENT_HW_REG | COMPONENT_SCHEDULER) // COMPONENT_CPU | COMPONENT_MMU

#define CHECK_SPR_ACCESS
#define CHECK_CP_COMMAND
#undef RECURSE_HR_ACCESS
#define DO_ASSERT_PAIRED_SINGLE

#define DO_DEBUGGER
#define DO_BREAKPOINTS
#define DO_CALL_STACK
#else
#define VERBOSITY VERBOSITY_MAX
#endif

#endif //GC__FLAGS_H
